/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface EncryptedDAOInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MIN_VOTING_DURATION"
      | "addMember"
      | "castVote"
      | "checkHasVoted"
      | "createProposal"
      | "getEncryptedVotes"
      | "getMemberCount"
      | "getProposal"
      | "getProposalCount"
      | "grantDecryptionAccess"
      | "hasVoted"
      | "isMember"
      | "isVotingEnded"
      | "joinDAO"
      | "memberCounter"
      | "members"
      | "proposalCounter"
      | "proposals"
      | "protocolId"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "MemberAdded"
      | "ProposalCreated"
      | "ProposalExecuted"
      | "VoteCast"
      | "VoteResultsDecrypted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "MIN_VOTING_DURATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addMember",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "castVote",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "checkHasVoted",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createProposal",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedVotes",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMemberCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getProposal",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getProposalCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "grantDecryptionAccess",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasVoted",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isMember",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isVotingEnded",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "joinDAO", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "memberCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "members",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "proposalCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "proposals",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "MIN_VOTING_DURATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addMember", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "castVote", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "checkHasVoted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedVotes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMemberCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProposalCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "grantDecryptionAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasVoted", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isMember", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isVotingEnded",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "joinDAO", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "memberCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "members", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proposalCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "proposals", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
}

export namespace MemberAddedEvent {
  export type InputTuple = [member: AddressLike];
  export type OutputTuple = [member: string];
  export interface OutputObject {
    member: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProposalCreatedEvent {
  export type InputTuple = [
    proposalId: BigNumberish,
    proposer: AddressLike,
    description: string,
    startTime: BigNumberish,
    endTime: BigNumberish
  ];
  export type OutputTuple = [
    proposalId: bigint,
    proposer: string,
    description: string,
    startTime: bigint,
    endTime: bigint
  ];
  export interface OutputObject {
    proposalId: bigint;
    proposer: string;
    description: string;
    startTime: bigint;
    endTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProposalExecutedEvent {
  export type InputTuple = [proposalId: BigNumberish, result: boolean];
  export type OutputTuple = [proposalId: bigint, result: boolean];
  export interface OutputObject {
    proposalId: bigint;
    result: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VoteCastEvent {
  export type InputTuple = [proposalId: BigNumberish, voter: AddressLike];
  export type OutputTuple = [proposalId: bigint, voter: string];
  export interface OutputObject {
    proposalId: bigint;
    voter: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VoteResultsDecryptedEvent {
  export type InputTuple = [
    proposalId: BigNumberish,
    yesVotes: BigNumberish,
    noVotes: BigNumberish,
    result: boolean
  ];
  export type OutputTuple = [
    proposalId: bigint,
    yesVotes: bigint,
    noVotes: bigint,
    result: boolean
  ];
  export interface OutputObject {
    proposalId: bigint;
    yesVotes: bigint;
    noVotes: bigint;
    result: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EncryptedDAO extends BaseContract {
  connect(runner?: ContractRunner | null): EncryptedDAO;
  waitForDeployment(): Promise<this>;

  interface: EncryptedDAOInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MIN_VOTING_DURATION: TypedContractMethod<[], [bigint], "view">;

  addMember: TypedContractMethod<
    [newMember: AddressLike],
    [void],
    "nonpayable"
  >;

  castVote: TypedContractMethod<
    [proposalId: BigNumberish, encryptedVote: BytesLike, voteProof: BytesLike],
    [void],
    "nonpayable"
  >;

  checkHasVoted: TypedContractMethod<
    [proposalId: BigNumberish, voter: AddressLike],
    [boolean],
    "view"
  >;

  createProposal: TypedContractMethod<
    [description: string, votingDuration: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  getEncryptedVotes: TypedContractMethod<
    [proposalId: BigNumberish],
    [
      [string, string] & { encryptedYesVotes: string; encryptedNoVotes: string }
    ],
    "view"
  >;

  getMemberCount: TypedContractMethod<[], [bigint], "view">;

  getProposal: TypedContractMethod<
    [proposalId: BigNumberish],
    [
      [bigint, string, string, bigint, bigint, boolean, bigint] & {
        id: bigint;
        proposer: string;
        description: string;
        startTime: bigint;
        endTime: bigint;
        executed: boolean;
        totalVoters: bigint;
      }
    ],
    "view"
  >;

  getProposalCount: TypedContractMethod<[], [bigint], "view">;

  grantDecryptionAccess: TypedContractMethod<
    [proposalId: BigNumberish],
    [void],
    "nonpayable"
  >;

  hasVoted: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  isMember: TypedContractMethod<[addr: AddressLike], [boolean], "view">;

  isVotingEnded: TypedContractMethod<
    [proposalId: BigNumberish],
    [boolean],
    "view"
  >;

  joinDAO: TypedContractMethod<[], [void], "nonpayable">;

  memberCounter: TypedContractMethod<[], [bigint], "view">;

  members: TypedContractMethod<
    [arg0: AddressLike],
    [[boolean, bigint] & { isMember: boolean; joinTime: bigint }],
    "view"
  >;

  proposalCounter: TypedContractMethod<[], [bigint], "view">;

  proposals: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        bigint,
        boolean,
        string,
        string,
        bigint
      ] & {
        id: bigint;
        proposer: string;
        description: string;
        startTime: bigint;
        endTime: bigint;
        executed: boolean;
        encryptedYesVotes: string;
        encryptedNoVotes: string;
        totalVoters: bigint;
      }
    ],
    "view"
  >;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MIN_VOTING_DURATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "addMember"
  ): TypedContractMethod<[newMember: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "castVote"
  ): TypedContractMethod<
    [proposalId: BigNumberish, encryptedVote: BytesLike, voteProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "checkHasVoted"
  ): TypedContractMethod<
    [proposalId: BigNumberish, voter: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "createProposal"
  ): TypedContractMethod<
    [description: string, votingDuration: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getEncryptedVotes"
  ): TypedContractMethod<
    [proposalId: BigNumberish],
    [
      [string, string] & { encryptedYesVotes: string; encryptedNoVotes: string }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMemberCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getProposal"
  ): TypedContractMethod<
    [proposalId: BigNumberish],
    [
      [bigint, string, string, bigint, bigint, boolean, bigint] & {
        id: bigint;
        proposer: string;
        description: string;
        startTime: bigint;
        endTime: bigint;
        executed: boolean;
        totalVoters: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getProposalCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "grantDecryptionAccess"
  ): TypedContractMethod<[proposalId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "hasVoted"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isMember"
  ): TypedContractMethod<[addr: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isVotingEnded"
  ): TypedContractMethod<[proposalId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "joinDAO"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "memberCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "members"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [[boolean, bigint] & { isMember: boolean; joinTime: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "proposalCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "proposals"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        bigint,
        boolean,
        string,
        string,
        bigint
      ] & {
        id: bigint;
        proposer: string;
        description: string;
        startTime: bigint;
        endTime: bigint;
        executed: boolean;
        encryptedYesVotes: string;
        encryptedNoVotes: string;
        totalVoters: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "MemberAdded"
  ): TypedContractEvent<
    MemberAddedEvent.InputTuple,
    MemberAddedEvent.OutputTuple,
    MemberAddedEvent.OutputObject
  >;
  getEvent(
    key: "ProposalCreated"
  ): TypedContractEvent<
    ProposalCreatedEvent.InputTuple,
    ProposalCreatedEvent.OutputTuple,
    ProposalCreatedEvent.OutputObject
  >;
  getEvent(
    key: "ProposalExecuted"
  ): TypedContractEvent<
    ProposalExecutedEvent.InputTuple,
    ProposalExecutedEvent.OutputTuple,
    ProposalExecutedEvent.OutputObject
  >;
  getEvent(
    key: "VoteCast"
  ): TypedContractEvent<
    VoteCastEvent.InputTuple,
    VoteCastEvent.OutputTuple,
    VoteCastEvent.OutputObject
  >;
  getEvent(
    key: "VoteResultsDecrypted"
  ): TypedContractEvent<
    VoteResultsDecryptedEvent.InputTuple,
    VoteResultsDecryptedEvent.OutputTuple,
    VoteResultsDecryptedEvent.OutputObject
  >;

  filters: {
    "MemberAdded(address)": TypedContractEvent<
      MemberAddedEvent.InputTuple,
      MemberAddedEvent.OutputTuple,
      MemberAddedEvent.OutputObject
    >;
    MemberAdded: TypedContractEvent<
      MemberAddedEvent.InputTuple,
      MemberAddedEvent.OutputTuple,
      MemberAddedEvent.OutputObject
    >;

    "ProposalCreated(uint256,address,string,uint256,uint256)": TypedContractEvent<
      ProposalCreatedEvent.InputTuple,
      ProposalCreatedEvent.OutputTuple,
      ProposalCreatedEvent.OutputObject
    >;
    ProposalCreated: TypedContractEvent<
      ProposalCreatedEvent.InputTuple,
      ProposalCreatedEvent.OutputTuple,
      ProposalCreatedEvent.OutputObject
    >;

    "ProposalExecuted(uint256,bool)": TypedContractEvent<
      ProposalExecutedEvent.InputTuple,
      ProposalExecutedEvent.OutputTuple,
      ProposalExecutedEvent.OutputObject
    >;
    ProposalExecuted: TypedContractEvent<
      ProposalExecutedEvent.InputTuple,
      ProposalExecutedEvent.OutputTuple,
      ProposalExecutedEvent.OutputObject
    >;

    "VoteCast(uint256,address)": TypedContractEvent<
      VoteCastEvent.InputTuple,
      VoteCastEvent.OutputTuple,
      VoteCastEvent.OutputObject
    >;
    VoteCast: TypedContractEvent<
      VoteCastEvent.InputTuple,
      VoteCastEvent.OutputTuple,
      VoteCastEvent.OutputObject
    >;

    "VoteResultsDecrypted(uint256,uint256,uint256,bool)": TypedContractEvent<
      VoteResultsDecryptedEvent.InputTuple,
      VoteResultsDecryptedEvent.OutputTuple,
      VoteResultsDecryptedEvent.OutputObject
    >;
    VoteResultsDecrypted: TypedContractEvent<
      VoteResultsDecryptedEvent.InputTuple,
      VoteResultsDecryptedEvent.OutputTuple,
      VoteResultsDecryptedEvent.OutputObject
    >;
  };
}
